/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil */

#ifndef _Included_cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil
#define _Included_cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil
 * Method:    encryption
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil_encryption
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_ffcs_is_mss_analyzer_utils_EncryptionUtil
 * Method:    decryption
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ffcs_is_mss_analyzer_utils_encryption_EncryptionUtil_decryption
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
