/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ffcs_is_sa_flink_scenes_xss_xssUtil_XSSInjectionUtil */

#ifndef _Included_cn_ffcs_is_sa_flink_scenes_xss_xssUtil_XSSInjectionUtil
#define _Included_cn_ffcs_is_sa_flink_scenes_xss_xssUtil_XSSInjectionUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ffcs_is_sa_flink_scenes_xss_xssUtil_XSSInjectionUtil
 * Method:    checkXss
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_ffcs_is_sa_flink_scenes_xss_xssUtil_XSSInjectionUtil_checkXss
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
